# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Verify SDK release

on: 
  pull_request:
  push:
    branches:
    - main
    - github_actions_build
    - github_actions_build_test
    tags:
      - 'v*'

jobs:    
  build_and_deploy:
    name: Build and deploy
    runs-on: macos-11

    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Checkout swift-docc repo
        uses: actions/checkout@v2
        with:
          repository: apple/swift-docc
          path: swift-docc

      - name: Generate Symbol Graphs
        run: |
          mkdir -p .build/symbol-graphs && \
          swift build \
            -Xswiftc -emit-symbol-graph \
            -Xswiftc -emit-symbol-graph-dir -Xswiftc .build/symbol-graphs \
            -Xswiftc "-sdk" -Xswiftc "`xcrun --sdk iphonesimulator --show-sdk-path`" -Xswiftc "-target" -Xswiftc "x86_64-apple-ios15.0-simulator"
      - name: Move Symbol Graphs
        run: |
          mkdir .build/core-symbol-graphs \
          && mv .build/symbol-graphs/Core* .build/core-symbol-graphs
          mkdir .build/authentication-symbol-graphs \
          && mv .build/symbol-graphs/Authentication* .build/authentication-symbol-graphs
          mkdir .build/adaptive-symbol-graphs \
          && mv .build/symbol-graphs/Adaptive* .build/adaptive-symbol-graphs
          mkdir .build/fido2-symbol-graphs \
          && mv .build/symbol-graphs/FIDO2* .build/fido2-symbol-graphs
      - name: Generate docc
        run: |
          cd swift-docc
          swift build

          mkdir ../.build/Adaptive.docc
          mkdir ../.build/Core.docc
          mkdir ../.build/FIDO2.docc
          mkdir ../.build/Authentication.docc

          git clone https://github.com/apple/swift-docc-render-artifact.git
          export DOCC_HTML_DIR="/Users/runner/work/verify-sdk-ios/verify-sdk-ios/swift-docc/swift-docc-render-artifact/dist"


          swift run docc convert ../.build/Core.docc \
            --fallback-display-name Core \
            --fallback-bundle-identifier com.ibm.Core \
            --fallback-bundle-version 1.0.0 \
            --additional-symbol-graph-dir ../.build/core-symbol-graphs

          swift run docc process-archive \ 
            transform-for-static-hosting \
            ../.build/Core.docc/.docc-build

          swift run docc convert ../.build/Adaptive.docc \
            --fallback-display-name Adaptive \
            --fallback-bundle-identifier com.ibm.Adaptive \
            --fallback-bundle-version 1.0.0 \
            --additional-symbol-graph-dir ../.build/adaptive-symbol-graphs

          swift run docc process-archive \
            transform-for-static-hosting \
            ../.build/Adaptive.docc/.docc-build

          swift run docc convert ../.build/Authentication.docc \
            --fallback-display-name Authentication \
            --fallback-bundle-identifier com.ibm.Authentication \
            --fallback-bundle-version 1.0.0 \
            --additional-symbol-graph-dir ../.build/authentication-symbol-graphs

          swift run docc process-archive \
            transform-for-static-hosting \
            ../.build/Authentication.docc/.docc-build

          swift run docc convert ../.build/FIDO2.docc \
            --fallback-display-name FIDO2 \
            --fallback-bundle-identifier com.ibm.FIDO2 \
            --fallback-bundle-version 1.0.0 \
            --additional-symbol-graph-dir ../.build/fido2-symbol-graphs

          swift run docc process-archive \
            transform-for-static-hosting \
            ../.build/FIDO2.docc/.docc-build

      - name: Push to I/O repo
        run: |
          git clone https://github.com/dylan-jb1/ibm-security-verify.github.io.git
          cd ibm-security-verify.github.io
          git checkout ios_sdk_test
          cd ..
          mkdir -p ibm-security-verify.github.io/ios/adaptive/docs
          mkdir -p ibm-security-verify.github.io/ios/core/docs
          mkdir -p ibm-security-verify.github.io/ios/fido2/docs
          mkdir -p ibm-security-verify.github.io/ios/authentication/docs
          cp -R ./.build/Adaptive.docc/.docc-build/. ibm-security-verify.github.io/ios/adaptive/docs
          cp -R ./.build/Core.docc/.docc-build/. ibm-security-verify.github.io/ios/core/docs
          cp -R ./.build/FIDO2.docc/.docc-build/. ibm-security-verify.github.io/ios/fido2/docs
          cp -R ./.build/Authentication.docc/.docc-build/. ibm-security-verify.github.io/ios/authentication/docs
          cd ibm-security-verify.github.io
          git add .
          git commit -m "Test commit"
          git status
          git config --get remote.origin.url
          git remote set-url origin https://${{ secrets.API_TOKEN_GITHUB }}@github.com/dylan-jb1/ibm-security-verify.github.io.git
          git push origin
          git config --get remote.origin.url
        